# Generated by Django 5.2.6 on 2025-09-11 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('deposit_date', models.DateField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dob', models.DateField()),
                ('joining_time', models.DateTimeField(auto_now=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER')], default='USER', null=True)),
                ('borrowed_books', models.ManyToManyField(blank=True, related_name='borrowed_books', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_acc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
