GENDER=(("Male","Male"),("Female","Female"))
USER_TYPE=(("ADMINISTRATOR","ADMINISTRATOR"),("USER","USER"))
TRANSACTION_TYPE=(("Debit","Debit"),("Credit","Credit"),("Penalty","Penalty"))
PAYMENT_STATUS=(("Pending","Pending"),("Success","Success"),("Cancelled","Cancelled"),("Failed","Failed"))
RATING=(("⭐⭐⭐⭐⭐","⭐⭐⭐⭐⭐"),("⭐⭐⭐⭐","⭐⭐⭐⭐"),("⭐⭐⭐","⭐⭐⭐"),("⭐⭐","⭐⭐"),("⭐","⭐"))
RETURN_STATUS=(("Returned","Returned"),("Not","Not"))