# Generated by Django 5.2.6 on 2025-09-11 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('borrow_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('added_by', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='categorys.category')),
            ],
        ),
    ]
